# Generated by Django 5.2.8 on 2025-11-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
