# Generated by Django 5.2.8 on 2025-11-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_document', 'Can view document'), ('can_edit_document', 'Can edit document'), ('can_create_document', 'Can create document'), ('can_delete_document', 'Can delete document')]},
        ),
    ]
